ci: Refresh circleci cache key
After https://github.com/os-autoinst/openQA/pull/3536 it seems
we need to explicitly invalidate the cached packages,
otherwise we get:

    error: Failed dependencies:
     perl(:MODULE_COMPAT_5.26.1) is needed by perl-Test-Fatal-0.014-lp152.3.2.noarch
     perl(:MODULE_COMPAT_5.26.1) is needed by perl-Hash-Merge-0.200-lp152.3.2.noarch