Show logs when docker compose up fails in the test_containers_compose
When docker-compose up fails we don't have information to investigate.
This PR show the logs when something wrong happens.

To test the failure case and see the logs. Introduce an "exit 1" as the first
line in the script containers/webui/run_openqa.sh. The logs will be showed
on the terminal as:

Creating webui_db_1 ... done
Creating webui_webui_db_init_1 ... done

ERROR: for webui  Container "XXXXXXXXXXXX" is unhealthy.
ERROR: Encountered errors while bringing up the project.
docker-compose exited with non-zero code 1, showing logs:
Attaching to webui_webui_db_init_1, webui_db_1
....

https://progress.opensuse.org/issues/95374