Fix hadolint check
Set the `HOME` variable explicitly as the current container image
otherwise fails with:
```
hadolint: getXdgDirectory:getHomeDirectory:getUserEntryForID: does not exist (No such file or directory)
make: *** [Makefile:309: test-check-containers] Error 1
Error: Process completed with exit code 2.
```