JobSettings: only index commonly-queried settings keys
See https://progress.opensuse.org/issues/121054 . When deploying
the bigint migration to Fedora, we found it failed, because some
entries in this index would now be larger than a hard limit in
postgresql:

ERROR:  index row size 2712 exceeds btree version 4 maximum 2704 for index "idx_job_id_value_settings"

These indexes are intended to speed up the `query_for_settings`
subquery in lib/OpenQA/Schema/ResultSet/JobSettings.pm - see
https://github.com/os-autoinst/openQA/pull/534 . Most queries
that go through that subquery will only query for keys in this
list. There is one path where arbitrary keys can be queried:
the API endpoint that allows for cancelling jobs by setting. I
suspect this isn't very heavily used, and when it is used, these
are still the most likely settings keys.

This requires a schema version bump and migration, all included.

Related progress issue: https://progress.opensuse.org/issues/121054

Signed-off-by: Adam Williamson <awilliam@redhat.com>